Anpassugen des CI-Tools
zweipunkt-gmbh/ci pull request #1
Opened 2022-03-28 07:58 UTC by mega-devkev

Anapssungen wie im Ticket ausgeführt und vorher auf alpine wegen der Image größe umgestellt

2022-03-28 11:47 UTC, megaxorg requested changes

2022-03-28 11:47 UTC, megaxorg commented on config/phpstan.neon
> +        - /src/public/engine/Library
Dieser Pfad existiert nur in SW5

2022-03-28 11:47 UTC, megaxorg commented on config/phpstan.neon
> +        - /src/public/custom/plugins/ZweiPunktOfferDocument/Resources/dompdf
Dieser Pfad existiert nur in SW5

2022-03-28 11:47 UTC, megaxorg commented on scripts/run.sh
> +    echo "No File with paths provided in /src"
Wo genau muss aus Sicht des Anwenders die ci.txt Datei abgelegt werden?

2022-03-28 11:47 UTC, megaxorg commented on scripts/run.sh
> +input="/src/ci.txt"
Der Name `input` ist wenig eindeutig, da es hier keinen Input gibt.

`directoryList`, `directories` etc wäre wohl eindeutiger.

2022-03-28 13:14 UTC, mega-devkev commented on config/phpstan.neon
> +        - /src/public/custom/plugins/ZweiPunktOfferDocument/Resources/dompdf
Der Pfand ist doch garnicht in der ci.txt hinterlegt

2022-03-28 13:14 UTC, mega-devkev commented on config/phpstan.neon
> +        - /src/public/engine/Library
Werden die Pfade trozdem durchsucht?

2022-03-28 13:19 UTC, megaxorg commented on config/phpstan.neon
> +        - /src/public/engine/Library
Du bist derjenige der mir die Frage beantworten können sollte :-)

2022-03-28 13:21 UTC, megaxorg commented on config/phpstan.neon
> +        - /src/public/custom/plugins/ZweiPunktOfferDocument/Resources/dompdf
Verstehe deinen Kommentar nicht...

Im CI Repository wird in einer Konfigurationsdatei ein Pfad angegeben den es im Code-Repository nicht gibt (bzw. nur in einem einzigen)

2022-03-28 13:23 UTC, megaxorg commented on scripts/run.sh
> +    echo "No File with paths provided in /src"
Dann sollte die Fehlermeldung auch genau das zurück geben :-)

Der Entwickler ruft i.d.R. weder das Docker Image per Hand auf (sondern über `tools/check.sh`), oder der Check wird im VCS durchgeführt. Da der Entwickler überhaupt nirgend einen Pfad angibt ist die Fehlermeldung "No File with paths provided in /src" nichtssagend und hilft nicht beim debuggen.

2022-03-31 11:00 UTC, megaxorg requested changes

2022-03-31 11:00 UTC, megaxorg commented on scripts/run.sh
> +  echo "tester: $line"
debug

2022-04-01 06:04 UTC, mega-devkev commented
Änderungen sind bereinigt

2022-04-01 09:28 UTC, megaxorg commented on scripts/run.sh
> + echo 'Directory /src does not exist.'
Bitte IMMER aussagefähige Fehlermeldungen verwenden mit denen der ENDANWENDER auch etwas anfangen kann.

2022-04-01 09:31 UTC, megaxorg requested changes

2022-04-01 09:31 UTC, megaxorg commented on config/.phpcs.xml
> +<!--    &lt;!&ndash; <file>public/custom/plugins/ZweiPunktPaymentMethodStatus</file> &ndash;&gt;-->
Der Code kann ganz raus. Wenn man ihn später braucht kann man in der History nachsehen

2022-04-01 09:31 UTC, megaxorg commented on config/phpmd.xml
> +<!--    <exclude-pattern>*dompdf/*</exclude-pattern>-->
Raus

2022-04-01 09:31 UTC, megaxorg commented on config/phpstan.neon
> +#    autoload_files:
Raus

2022-04-01 09:31 UTC, megaxorg commented on config/phpstan_include.neon
> +#    autoload_files:
Raus

Hier kann man auch mit einem Kommentar in den Dateien nochmal darauf hinweisen, dass die Änderungen in beiden Dateien (mit und ohne include) zweimal gemacht werden müssen udn warum das notwendig ist.

2022-04-01 11:08 UTC, mega-devkev commented on config/phpstan.neon
> +#    autoload_files:
ich kann das parameters aber nicht raus nehmen sonnt kann die Datei von phpstan nicht mehr gelesenwerden.

2022-04-01 12:23 UTC, megaxorg commented on config/phpstan.neon
> +#    autoload_files:
Es geht um den auskommentierten Teil (autoload)

2022-04-01 14:13 UTC, merged